config: {}
networks:
- config:
    ipv4.address: 10.0.0.1/24
    ipv6.address: none
  description: ""
  name: incusbr0
  type: ""
  project: default
storage_pools:
- config:
    source: /dev/disk/by-id/google-freedb-data-1
  description: ""
  name: pd-standard
  driver: zfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: incusbr0
      type: nic
    root:
      path: /
      pool: pd-standard
      type: disk
  name: default
projects: []
cluster: null